- name: Install debconf-utils.
  become: yes
  apt: name=debconf-utils state=latest update_cache=yes

- name: Preset root password.
  become: yes
  shell: 'echo "mysql-server-5.7 mysql-server/root_password password root" | debconf-set-selections'

- name: Confirm root password.
  become: yes
  shell: 'echo "mysql-server-5.7 mysql-server/root_password_again password root" | debconf-set-selections'

- name: Install MySQL packages.
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - mysql-server-5.7
    - mysql-client-5.7
    - libmysqlclient-dev
    - python-mysqldb

- name: Copy MySQL root profile.
  template: src=root.cnf dest=~/.my.cnf mode=0600

- name: Configure MySQL.
  become: yes
  template: src=mysqld.cnf
            dest=/etc/mysql/mysql.conf.d/mysqld.cnf
            owner=root
            group=root
            mode=0644
            backup=yes
  notify:
    - restart mysql

- name: Remove test db.
  mysql_db: name=test state=absent
  notify:
    - restart mysql

- name: Create SkunkWerkz db.
  mysql_db: name=skunkwerkz state=present
  notify:
    - restart mysql
